services:
  postgres:
    image: postgres:16
    container_name: database
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cache
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"

  api:
    build: .
    container_name: favorites-producs
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    networks:
      - default

volumes:
  postgres_data:
